packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  styled-components@*:
    dependencies:
      react-is: '*'
  '@n1ru4l/graphql-live-query@*':
    dependencies:
      tslib: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
