packageExtensions:
  "@graphql-tools/url-loader@*":
    dependencies:
      node-fetch: "*"
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  cosmiconfig-typescript-loader@*:
    dependencies:
      ts-node: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
